### ISSUE TITLE
Mod crash when using Magma launcher

### ISSUE THREAD

**Issue by XVMINwav** [Sasai-Kudasai-BM/Water-Physics-Overhaul#52]
Hi, I have recently been using the water physics overhaul mod on my server and it has been doing very well. Yesterday I ported the forge server over to a magma server which supports both mods and plugins at the same time. Although nothing looked wrong after the switch I came across an issue with the water physics mod. It stopped flowing and became bugged and stationary. While reading the logs I saw it might had something to do with the Bukkit instance that is automatically loaded. 
After searching for a while I still have not found a fix for it. I would like to know if it is fixable or if it is just not compatible with any non forge modloader or pluginloader.

Here the log:
[SKDS-Worker-0/ERROR] [SKDS Core/]: Exeption while executing task 
net.minecraft.crash.ReportedException: Exception while updating neighbours
	at net.minecraft.world.World.func_190524_a(World.java:501) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:custom.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_195593_d(World.java:430) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:custom.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.skds.wpo.fluidphysics.FFluidBasic.applyAction(FFluidBasic.java:92) ~[wpo:0.3.0] {re:classloading}
	at net.skds.core.util.blockupdate.BasicExecutor.setState(BasicExecutor.java:44) ~[skds_core:0.2.0] {re:classloading}
	at net.skds.wpo.fluidphysics.FFluidDefault.execute(FFluidDefault.java:175) ~[wpo:0.3.0] {re:classloading}
	at net.skds.wpo.fluidphysics.FFluidBasic.run(FFluidBasic.java:115) ~[wpo:0.3.0] {re:classloading}
	at net.skds.wpo.fluidphysics.FluidTask$DefaultTask.run(FluidTask.java:66) ~[wpo:0.3.0] {re:classloading}
	at net.skds.core.multithreading.UniversalWorkerThread.takeTasksStack(UniversalWorkerThread.java:95) [skds_core:0.2.0] {re:classloading}
	at net.skds.core.multithreading.UniversalWorkerThread.run(UniversalWorkerThread.java:57) [skds_core:0.2.0] {re:classloading}
Caused by: java.lang.IllegalStateException: BlockPhysicsEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:579) ~[forge:?] {re:classloading}
	at net.minecraft.world.World.func_190524_a(World.java:479) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:custom.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	... 8 more

**Comment by blackmidiuser** [comment]
> Hi, I have recently been using the water physics overhaul mod on my server and it has been doing very well. Yesterday I ported the forge server over to a magma server which supports both mods and plugins at the same time. Although nothing looked wrong after the switch I came across an issue with the water physics mod. It stopped flowing and became bugged and stationary. While reading the logs I saw it might had something to do with the Bukkit instance that is automatically loaded. After searching for a while I still have not found a fix for it. I would like to know if it is fixable or if it is just not compatible with any non forge modloader or pluginloader.
> 
> Here the log: [SKDS-Worker-0/ERROR] [SKDS Core/]: Exeption while executing task net.minecraft.crash.ReportedException: Exception while updating neighbours at net.minecraft.world.World.func_190524_a(World.java:501) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:custom.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.world.World.func_195593_d(World.java:430) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:custom.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A} at net.skds.wpo.fluidphysics.FFluidBasic.applyAction(FFluidBasic.java:92) ~[wpo:0.3.0] {re:classloading} at net.skds.core.util.blockupdate.BasicExecutor.setState(BasicExecutor.java:44) ~[skds_core:0.2.0] {re:classloading} at net.skds.wpo.fluidphysics.FFluidDefault.execute(FFluidDefault.java:175) ~[wpo:0.3.0] {re:classloading} at net.skds.wpo.fluidphysics.FFluidBasic.run(FFluidBasic.java:115) ~[wpo:0.3.0] {re:classloading} at net.skds.wpo.fluidphysics.FluidTask$DefaultTask.run(FluidTask.java:66) ~[wpo:0.3.0] {re:classloading} at net.skds.core.multithreading.UniversalWorkerThread.takeTasksStack(UniversalWorkerThread.java:95) [skds_core:0.2.0] {re:classloading} at net.skds.core.multithreading.UniversalWorkerThread.run(UniversalWorkerThread.java:57) [skds_core:0.2.0] {re:classloading} Caused by: java.lang.IllegalStateException: BlockPhysicsEvent cannot be triggered asynchronously from another thread. at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:579) ~[forge:?] {re:classloading} at net.minecraft.world.World.func_190524_a(World.java:479) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.skds_core.json:custom.WorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A} ... 8 more

It needs SKDS Core
